import { describe, expect, it } from 'vitest'
import source from '../../../public/assets/games/watermelon/engine.js?raw'
import data, { type ParticleSnapshot, type WatermelonDrop } from '@gamewatermelon-fixtures'
import spawnVectors from '@gamewatermelon-spawn-vectors'

interface Engine {
  VERSION: string
  initial(seed: string): ParticleSnapshot
  replay(seed: string, state: ParticleSnapshot, toTick: number, drops: WatermelonDrop[]): ParticleSnapshot
  restore(seed: string, state: ParticleSnapshot): unknown
  snapshot(game: unknown): ParticleSnapshot
  spawnLevel(seed: string, index: number): number
}
const engine = new Function(`${source}; return MelonMelt;`)() as Engine

describe('水果种子随机分布', () => {
  it('与 Go 共用精确向量，跨十进制边界且支持乱序索引查询', () => {
    for (const vector of spawnVectors) {
      expect(vector.levels.map((_, i) => engine.spawnLevel(vector.seed, vector.start_index + i))).toEqual(vector.levels)
      for (let i = vector.levels.length - 1; i >= 0; i--) {
        expect(engine.spawnLevel(vector.seed, vector.start_index + i)).toBe(vector.levels[i])
      }
    }
  })

  it('修复固定种子开头二十颗全是最小水果，仍允许自然连出相同水果', () => {
    const seed = '0123456789abcdef0123456789abcdef'
    const opening = Array.from({ length: 20 }, (_, i) => engine.spawnLevel(seed, i))
    expect(new Set(opening.slice(0, 12)).size).toBe(3)
    expect(Array.from({ length: 20 }, (_, i) => engine.spawnLevel(seed, i))).toEqual(opening)
    expect(Array.from({ length: 20 }, (_, i) => engine.spawnLevel('00000000000000000000000000000000', i))).not.toEqual(opening)
    expect(opening.some((fruit, i) => i > 0 && fruit === opening[i - 1])).toBe(true)
  })

  it('大量相邻投放接近均匀独立的三种低阶水果，不产生编号导致的连续固定批次', () => {
    const counts = [0, 0, 0]
    let transitions = 0
    for (let s = 0; s < 32; s++) {
      const seed = s.toString(16).padStart(32, '0')
      let previous = -1
      for (let i = 0; i < 2048; i++) {
        const level = engine.spawnLevel(seed, i)
        if (!Number.isInteger(level) || level < 0 || level > 2) throw new Error('Only grape/cherry/mandarin may spawn')
        counts[level]++
        if (previous >= 0 && level !== previous) transitions++
        previous = level
      }
    }
    for (const count of counts) {
      expect(count / 65536).toBeGreaterThan(.30)
      expect(count / 65536).toBeLessThan(.37)
    }
    expect(transitions / (32 * 2047)).toBeGreaterThan(.60)
    expect(transitions / (32 * 2047)).toBeLessThan(.73)
  })
})

describe('实际发布的软体引擎与原生 Go 服务端逐粒子一致', () => {
  it('同一夹具包含长局、拥挤碰撞、最高级合成与精确结束时刻', () => {
    expect(data.version).toBe(engine.VERSION)
    expect(data.fixtures.length).toBeGreaterThanOrEqual(7)
    expect(data.fixtures.some(f => f.segments[f.segments.length - 1].expected.tick >= 18000)).toBe(true)
    expect(data.fixtures.some(f => f.segments[f.segments.length - 1].expected.highest === 8)).toBe(true)
    expect(data.fixtures.some(f => f.segments[f.segments.length - 1].expected.phase === 'over')).toBe(true)
    for (const fixture of data.fixtures) expect(fixture.seed).toMatch(/^[a-f0-9]{32}$/)
  })

  for (const fixture of data.fixtures) {
    it(fixture.name, () => {
      let state = fixture.initial_state ?? engine.initial(fixture.seed)
      for (const segment of fixture.segments) {
        // Expected states are generated by uninterrupted play; each actual
        // segment starts from the compact serialized particle state instead.
        state = engine.replay(fixture.seed, state, segment.to_tick, segment.drops)
        expect(state, `tick ${segment.to_tick}`).toEqual(segment.expected)
        const restored = engine.restore(fixture.seed, JSON.parse(JSON.stringify(state)) as ParticleSnapshot)
        expect(engine.snapshot(restored)).toEqual(state)
      }
    }, 60000)
  }

  it('零时长存档可以接受一次投放，58 tick 冷却边界与任意切段一致', () => {
    const seed = data.fixtures[0].seed
    const initial = engine.initial(seed)
    const first = engine.replay(seed, initial, 0, [{ tick: 0, x: 180 }])
    expect(first.tick).toBe(0)
    expect(first.drops).toBe(1)
    expect(first.highest).toBe(-1)
    const before = JSON.stringify(first)
    expect(() => engine.replay(seed, first, 57, [{ tick: 57, x: 0 }])).toThrow()
    expect(JSON.stringify(first)).toBe(before)
    const second = engine.replay(seed, first, 58, [{ tick: 58, x: 0 }])
    const whole = engine.replay(seed, initial, 120, [{ tick: 0, x: 180 }, { tick: 58, x: 0 }])
    expect(engine.replay(seed, second, 120, [])).toEqual(whole)
  })
})
